prometheus_version: latest
prometheus_web_external_url: 'http://prometheus.itili4.ru:9090'
prometheus_targets: 
  node:
    - targets:
        - itili4.ru:9100
      labels:
        env: Proxy
    - targets:
        - wordpress.itili4.ru:9100
      labels:
        env: Frontend
    - targets:
        - db01.itili4.ru:9100
        - db02.itili4.ru:9100
      labels:
        env: DB Servers
    - targets:
        - gitlab.itili4.ru:9100
      labels:
        env: GitlabServer
    - targets:
        - grunner.itili4.ru:9100
      labels:
        env: GitlabRunner
    - targets:
        - dbha.itili4.ru:9100
      labels:
        env: MysqlReversProxy
        
prometheus_alertmanager_config:
  - static_configs:
      - targets:
          - localhost:9093
#     proxy_url: "127.0.0.2"

grafana_security:
  admin_user: admin
  admin_password: "admin"

grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://192.168.102.16:9090'
    basicAuth: false


alertmanager_version: latest
alertmanager_web_external_url: 'http://alertmanager.itili4.ru:9093/'
alertmanager_receivers:
- name: 'email'
  email_configs:
  - to: 'sd@itili4.ru'
    from: 'alert@itili4.ru'
    smarthost: 'mx.itili4.ru:25'
    auth_username: 'user'
    auth_identity: 'alert'
    auth_password: 'pass'
alertmanager_route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 60m
  receiver: 'email'

