---

nginx_revproxy_sites:                                         # List of sites to reverse proxy
  itili4.ru:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - itili4.ru
      - www.itili4.ru
    upstreams:                                                # List of Upstreams
      - {backend_address: wordpress.itili4.ru, backend_port: 80}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "beresnevia.it@gmail.com"              # Set email for letencrypt cert
  grafana.itili4.ru:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - grafana.itili4.ru
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.102.16, backend_port: 3000}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "beresnevia.it@gmail.com"
  prometheus.itili4.ru:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - prometheus.itili4.ru
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.102.16, backend_port: 9090}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "beresnevia.it@gmail.com"
  alertmanager.itili4.ru:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - alertmanager.itili4.ru
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.102.16, backend_port: 9093}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "beresnevia.it@gmail.com"
  gitlab.itili4.ru:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - gitlab.itili4.ru
    upstreams:                                                # List of Upstreams
      - {backend_address: 192.168.102.14, backend_port: 80}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "beresnevia.it@gmail.com"
  wordpress.itili4.ru:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - wordpress.itili4.ru
    upstreams:                                                # List of Upstreams
      - {backend_address: wordpress.itili4.ru, backend_port: 80}
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "beresnevia.it@gmail.com"
  

nginx_revproxy_certbot_auto: false

# Remove WebRoot Sites
nginx_revproxy_remove_webroot_sites: true

# De-activate Sites
nginx_revproxy_de_activate_sites: false

privoxy_listen_address: "192.168.101.11"

addsoft: "no"
dole: "no"