---
# Проверяем налчиие директорий для Grafana
- name: Ensure grafana configuration directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: grafana
  with_items:
    - "/etc/grafana"
    - "/etc/grafana/datasources"
    - "/etc/grafana/provisioning"
    - "/etc/grafana/provisioning/datasources"
    - "/etc/grafana/provisioning/dashboards"
    - "/etc/grafana/provisioning/notifiers"
    - "/etc/grafana/provisioning/plugins"
# Создаем(копируем и заполняем шаблон) конфигурационного файла
- name: Create grafana main configuration file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0640
  no_log: true
  notify: restart grafana
# Создаем папки необходимые для Grafana
- name: Create grafana directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "grafana"
    group: "grafana"
  with_items:
    - "{{ grafana_logs_dir }}"
    - "{{ grafana_data_dir }}"
    - "{{ grafana_data_dir }}/dashboards"
    - "{{ grafana_data_dir }}/plugins"
# Создаем папки необходимые для Grafana
- block:
    - name: Create grafana socket directory
      file:
        path: "{{ grafana_server.socket | dirname }}"
        state: directory
        mode: 0775
        owner: "grafana"
        group: "grafana"

    - name: Ensure grafana socket directory created on startup
      template:
        src: tmpfiles.j2
        dest: /etc/tmpfiles.d/grafana.conf
        owner: root
        group: root
        mode: 0644
  when:
    - grafana_server.protocol is defined and grafana_server.protocol == 'socket'
    - grafana_server.socket | dirname != '/var/run'
# Провемяем что автозапуск сервиса разрешен и запускаем сервис
- name: Enable and start Grafana systemd unit
  systemd:
    name: grafana-server
    enabled: true
    state: started
    daemon_reload: true
