---
# Удаляем старые версии сервиса
- name: Remove conflicting grafana packages
  package:
    name: grafana-data
    state: absent
  register: _old_grafana_pkgs
# Подключаем репозиторий для загрузруки пакетов
- name: Add Grafana repository file [RHEL/CentOS]
  template:
    src: "{{ grafana_yum_repo_template }}"
    dest: "/etc/yum.repos.d/{{ grafana_yum_repo_template | basename | regex_replace('\\.j2$', '') }}"
    force: true
    backup: true
  when:
    - ansible_pkg_mgr in ['yum', 'dnf']
    - grafana_manage_repo
# Устанавливаем сервис
- name: Install Grafana
  package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: restart grafana
