---
# Проверяем заданы ли переменные в корректном формате
- name: Check variable types
  assert:
    that:
      - grafana_server is mapping
      - grafana_database is mapping
      - grafana_security is mapping
# Вызвать ошибку если не назначены источники данных и запрошена устанвока дашбордов
- name: Fail when datasources aren't configured when dashboards are set to be installed
  fail:
    msg: "You need to specify datasources for dashboards!!!"
  when: grafana_dashboards != [] and grafana_datasources == []
# Вызвать ошибку если не верны или не заданы параметры учетной записи администратора
- name: Fail when grafana admin user isn't set
  fail:
    msg: "Please specify grafana admin user (grafana_security.admin_user)"
  when:
    - grafana_security.admin_user == '' or
      grafana_security.admin_user is not defined
- name: Fail when grafana admin password isn't set
  fail:
    msg: "Please specify grafana admin password (grafana_security.admin_password)"
  when:
    - grafana_security.admin_password == '' or
      grafana_security.admin_password is not defined
# Вызвать ошибку если использованы некорретный переменные при описании источников данных
- name: Fail on incorrect variable types in datasource definitions
  fail:
    msg: "Boolean variables in grafana_datasources shouldn't be passed as strings. Please remove unneeded apostrophes."
  when: ( item.isDefault is defined and item.isDefault is string ) or
        ( item.basicAuth is defined and item.basicAuth is string )
  with_items: "{{ grafana_datasources }}"
# Вызвать ошибку если некорретно настроена база данных сервиса
- name: Fail on bad database configuration
  fail:
    msg: "Wrong database configuration. Please look at http://docs.grafana.org/installation/configuration/#database"
  when: ( grafana_database.type == "sqlite3" and grafana_database.url is defined ) or
        ( grafana_database.type != "sqlite3" and grafana_database.path is defined ) or
        ( grafana_database.type == "sqlite3" and grafana_database.host is defined ) or
        ( grafana_database.type == "sqlite3" and grafana_database.user is defined ) or
        ( grafana_database.type == "sqlite3" and grafana_database.password is defined ) or
        ( grafana_database.type == "sqlite3" and grafana_database.server_cert_name is defined )
# Вызвать ошибку если некорретно задан домен для сервиса
- name: Fail when grafana domain isn't properly configured
  fail:
    msg: "Check server configuration. Please look at http://docs.grafana.org/installation/configuration/#server"
  when:
    - grafana_server.root_url is defined
    - grafana_server.root_url is search(grafana_server.domain)

# Вызвать ошибку если сервис настроен на использование сокетов, а соответствующие переменные не определены.
- name: Fail if grafana_server.socket not defined when in socket mode
  fail:
    msg: "You need to configure grafana_server.socket when grafana_server.protocol is set to 'socket'"
  when:
    - grafana_server.protocol is defined and grafana_server.protocol == 'socket'
    - grafana_server.socket is undefined or grafana_server.socket == ''
