---
- name: Gimme CERTS
# Устанавливаем пакеты для получения сертификатов
- name: Install certbot-auto
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/bin/certbot-auto
    mode: "a+x"
  when: nginx_revproxy_certbot_auto
# Устанавливаем пакеты для получения сертификатов
- name: Install certbot from repository
  yum:
    name: "{{ nginx_revproxy_certbot_packages }}"
    state: present
  when: not nginx_revproxy_certbot_auto
# Перезапускаем Nginx
- name: Reload Nginx
  service:
    name: nginx
    state: restarted
# Получаем список сайтов для сертификатов
- name: Get Active Sites
  command: ls -1 /etc/nginx/conf.d/
  changed_when: "active.stdout_lines != nginx_revproxy_sites.keys()|sort()"
  check_mode: false
  register: active

# Запрашиваем сертификаты
- name: Generate certs (first time)
  command: |
    certbot{{ '-auto' if nginx_revproxy_certbot_auto else '' }} certonly
    --webroot -w /var/www/{{ item.key }}
    -d {{ item.value.domains | join(' -d ') }}
    --email {{ item.value.letsencrypt_email }}
    --non-interactive --cert-name {{ item.key }}
    --agree-tos creates=/etc/letsencrypt/live/{{ item.key }}/fullchain.pem --test-cert
  with_dict: "{{ nginx_revproxy_sites }}"
  when: item.value.letsencrypt | default(False)

# Обновляем конфигурационные файлы сайтов, прописывая в них необходимые опции, для работы с сертификатами.
- name: Update Site Config
  template:
    src: reverseproxy_ssl.conf.j2
    dest: /etc/nginx/conf.d/{{ item.key }}.conf
    owner: root
    group: root
    mode: 0640
  with_dict: "{{ nginx_revproxy_sites }}"
  notify: Reload Nginx
  when:
    - item.value.letsencrypt | default(False)

# Прописывает в cron автозапуск скрипта для получения сертификатов и их автоматического продления.
- name: Insert cert-bot renew in crontab
  cron:
    name: "cert-bot renew"
    job: "certbot{{ '-auto --test-cert' if nginx_revproxy_certbot_auto else '' }} renew --post-hook \"systemctl reload nginx\" >> /var/log/letsencrypt/letsencrypt-update.log 2>&1"
    hour: "3"
    minute: "30"
    weekday: "1"
