---
# Устраняем проблемы с Selinux и получаем проблемы с безопасностью, но если логировать и парсить audit.log то все будет под контролем.
- name: Selinux to permissive mode
  selinux:
    policy: targeted
    state: permissive
# Перезагружаемся и ждем для продолжения, если не ждать падает в ошибку.
- name: Reboot machine and wait 60 sec
  ansible.builtin.reboot:
    reboot_timeout: 60
# Добавляем репозитории
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
# Устанавливаем Nginx
- name: Install Nginx
  yum:
    name:
      - nginx
    state: present
  register:
    nginxinstalled

# Проверяем что сервис разрешен для автозапуска.
- name: Enable service nginx and ensure it is not masked
  become: true
  systemd:
    name: nginx
    enabled: yes
    masked: no

# Создаем директории необходимые для работы, костыльный вариант, надо переписать.
- name: Set up nginx directories
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0640
  with_items:
    - sites-available
    - sites-enabled

# Заполняем и загружаем конфигурационные файлы для сайтов
- name: Add Site Config
  template:
    src: reverseproxy.conf.j2
    dest: /etc/nginx/conf.d/{{ item.key }}.conf
    owner: root
    group: root
    mode: 0640
  with_dict: "{{ nginx_revproxy_sites }}"
  register:
    siteconfig
  when:
    - nginxinstalled is success

# Создаем корневые директории для получения сертификатов
- name: Create WebRoot sites
  file:
    dest: /var/www/{{ item.key }}/.well-known
    mode: 0775
    state: directory
    owner: nginx
    group: nginx
  with_dict: "{{ nginx_revproxy_sites }}"
  notify: Reload Nginx
  when:
    - nginxinstalled is success

#  Провемяем/устанавливаем необходимые права доступа
- name: WebRoot Permissions Sites
  file:
    dest: /var/www/{{ item.key }}
    mode: 0775
    state: directory
    owner: nginx
    group: nginx
    recurse: true
  with_dict: "{{ nginx_revproxy_sites }}"
  notify: Reload Nginx
  when:
    - nginxinstalled is success
# Подключаем задачи для получения сертификатов
- name: Exucte task if letsencrypt var equal to "get".
  include_tasks: letsencrypt.yml
  when: dole == "get"