---
# Проверяем назанчения сервера на котором планируется устанока
# Если Клиент то устнавливаем только клиентскую часть без точек обмена
- name: Install client
  include_tasks: client.yml
  when: ansible_facts['hostname'] == {{ rsync_sender_hostname }}
# Если сервер то конфигурируем точки обмена
- name: Install server
  include_tasks: server.yml
  when: ansible_facts['hostname'] != {{ rsync_sender_hostname }}
