---
# Устанавливаем сервис
- name: rsyncd | install rsync
  yum:
    pkg: rsync
    state: present
# Настраиваем директорию хранения файлов журнала
- name: rsyncd | create log directory
  file:
    path: /var/log/rsyncd
    state: directory
    mode: 0755
# Настраиваем точки обмена файлами
- name: rsyncd | configure shares
  template:
    dest: /etc/rsyncd.conf
    src: etc-rsyncd-conf.j2
    mode: 0644
# Настраиваем периодичность хранения файлов журнала
- name: rsyncd | configure logrotate
  template:
    backup: false
    dest: /etc/logrotate.d/rsyncd
    src: logrotated-rsyncd.j2
    mode: 0644
# Устанавлвиаем парава доступа на файл с "секретами"
- name: Copy file with owner and permissions
  copy:
    src: rsyncd.scrt
    dest: /etc/rsyncd.scrt
    owner: root
    group: root
    mode: '0600'
# Настраиваем Selinux
- name: rsyncd | selinux allow network connect
  seboolean:
    name: rsync_export_all_ro
    state: true
    persistent: true

- name: Semanage to permissive mode ro rsync
  ansible.builtin.command: semanage permissive -a rsync_t
# Проверяем наличия разрешени на автозапуск и запускаем сервис
- name: rsyncd | start and enable service
  service:
    name: rsyncd
    enabled: true
    state: started
