---
# tasks file for rsync-server

- name: rsyncd | install rsync
  yum:
    pkg: rsync
    state: present

- name: rsyncd | create log directory
  file:
    path: /var/log/rsyncd
    state: directory
    mode: 0755

- name: rsyncd | configure shares
  template:
    dest: /etc/rsyncd.conf
    src: etc-rsyncd-conf.j2
    mode: 0644
    # No need to reload, file is re-read on each client connection.

- name: rsyncd | configure logrotate
  template:
    backup: false
    dest: /etc/logrotate.d/rsyncd
    src: logrotated-rsyncd.j2
    mode: 0644

- name: Copy file with owner and permissions
  copy:
    src: rsyncd.scrt
    dest: /etc/rsyncd.scrt
    owner: root
    group: root
    mode: '0600'

- name: rsyncd | selinux allow network connect
  seboolean:
    name: rsync_export_all_ro
    state: true
    persistent: true
#  when: selinux_enabled

- name: Semanage to permissive mode ro rsync
  ansible.builtin.command: semanage permissive -a rsync_t

- name: rsyncd | start and enable service
  service:
    name: rsyncd
    enabled: true
    state: started
