{
 "title": "WordPress exporter dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of comments",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "wp_num_comments_metric" }
   ]
  },
  {
   "title": "WordPress number of registered users",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "wp_num_users_metric" }
   ]
  },
  {
   "title": "Number of WordPress posts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wp_num_posts_metric" }
   ]
  }
 ]
}