---
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Ensure Httpd package is installed.
  yum:
    name: httpd
    state: present

- name: Enable service httpd and ensure it is not masked
  become: true
  systemd:
    name: httpd
    enabled: yes
    masked: no

- name: Start httpd
  service:
    name: httpd
    state: started

