---
#  - name: Add Sample Page
#    copy:
#      src: index.html
#      dest: /var/www/wordpress.itili4.ru/public_html/index.html
#      owner: apache
#      group: apache
#      mode: 0755
- name: Download and unpack latest WordPress
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/wordpress.itili4.ru/public_html"
    owner: apache
    group: apache
    mode: 0755
    remote_src: yes
#    creates: "/var/www/{{ http_host }}/wordpress"

- name: Move wordpress to webroot
  #command: cp /var/www/wordpress.itili4.ru/public_html/wordpress/* /var/www/wordpress.itili4.ru/public_html/
  copy:
    src: /var/www/wordpress.itili4.ru/public_html/wordpress/
    dest: /var/www/wordpress.itili4.ru/public_html/
    remote_src: yes
    owner: apache
    group: apache

- name: Set up wp-config
  template:
    src: "wp-config.php"
    dest: "/var/www/wordpress.itili4.ru/public_html/wp-config.php"

- name: WebRoot Permissions Sites
  file:
    dest: /var/www/wordpress.itili4.ru/public_html/
    mode: 0755
    state: directory
    owner: apache
    group: apache
    recurse: true

- name: Reload Apache
  service:
    name: httpd
    state: reloaded