---
# Добавляеи ключи от репозитория с пакетами для PHP 7.4 и выше
- name: Import remi GPG key.
  rpm_key:
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
    state: present
# Устанавливаем новый репозиторий
- name: Install remi repo.
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
# Устанавливаем PHP 7.4
- name: Ensure PHP packages is installed.
  yum:
    name: '{{ item }}'
    state: present
    update_cache: true
    enablerepo: "remi"
  loop:
    - php74-php
    - php74-php-cli
    - php74-php-mysqlnd
    - php74-php-pear
    - php74-php-mbstring 
    - php74-php-mcrypt 
    - php74-php-devel 
    - php74-php-xml 
    - php74-php-gd
    - php74-php-fpm
    - php74-php-zip
    - php74-php-curl
    - php74-php-bcmath
    - php74-php-json