--- 
- name: first task
  hosts: reversproxy
  roles: 
#    -  { role: install-node-exporter, become: yes }
#    -  install-privoxy
#    -  { role: install-nginx-revproxy, become: yes }
#- name: Install MySQL Cluster
#  hosts: dbservers
#  roles: 
#   -  { role: install-node-exporter, become: yes } 
#   -  { role: install-mysql, become: yes }
#  environment:
#        http_proxy: http://192.168.101.11:8118
#        https_proxy: http://192.168.101.11:8118
#
#- name: Setup Application server
#  hosts: frontend
#  roles:
#    - { role: install-node-exporter, become: yes }
#    - { role: install-wordpress, become: yes }
#  environment:
#        http_proxy: http://192.168.101.11:8118
#        https_proxy: http://192.168.101.11:8118
#
- name: Setup Monitoring server
  hosts: gpaservers
  roles:
    - { role: install-node-exporter, become: yes }
    - { role: install-prometheus, become: yes }
  environment:
        http_proxy: http://192.168.101.11:8118
        https_proxy: http://192.168.101.11:8118