---
- hosts: reverseproxy
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install privoxy
    yum:
      name: privoxy
      state: present

  - name: Copy config file
    ansible.builtin.copy:
      src: templates/privoxy.config
      dest: /etc/privoxy/config
      owner: centos
      group: centos
      mode: '0644'

  - name: Start privoxy
    service:
      name: privoxy
      state: started