---
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install privoxy
  yum:
    name: privoxy
    state: present

- name: Copy config file
  template:
    src: config.j2
    dest: /etc/privoxy/config
    owner: centos
    group: centos
    mode: '0644'

- name: Enable service privoxy and ensure it is not masked
  systemd:
    name: privoxy
    enabled: yes
    masked: no

- name: Start privoxy
  systemd:
    name: privoxy
    state: started